from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from models import FunctionAnalysis


DEFAULT_TEST_SIZE = 64
DEFAULT_TEST_SEED = 20260803
TESTBENCH_PROFILES = ("smoke", "standard", "full")


@dataclass(frozen=True)
class TestbenchScenario:
    name: str
    pattern: str
    size_mode: str
    seed_offset: int = 0


@dataclass(frozen=True)
class TestbenchSource:
    filename: str
    source: str
    support_files: dict[str, str] = field(default_factory=dict)
    manifest: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ParameterSpec:
    raw: str
    name: str
    c_type: str
    dimensions: list[str]
    is_pointer: bool = False
    direction: str = "input"

    @property
    def is_array(self) -> bool:
        return bool(self.dimensions)

    @property
    def has_storage(self) -> bool:
        return self.is_array or self.is_pointer

    @property
    def storage_type(self) -> str:
        return _strip_type_qualifiers(self.c_type)

    @property
    def is_floating_point(self) -> bool:
        return _is_float_type(self.storage_type)


def generate_local_testbench(
    source_text: str,
    source_stem: str,
    top_function: FunctionAnalysis,
    profile: str = "full",
    seed: int = DEFAULT_TEST_SEED,
) -> TestbenchSource:
    if profile not in TESTBENCH_PROFILES:
        raise ValueError(f"Unsupported testbench profile: {profile}")
    if seed < 0 or seed > 0xFFFFFFFF:
        raise ValueError("Testbench seed must be between 0 and 4294967295.")

    body = _extract_function_body(source_text, top_function.name)
    specs = [
        _with_direction(_parse_parameter(parameter), body)
        for parameter in top_function.parameters
    ]
    scenarios = _scenarios_for_profile(profile)
    golden_name = f"{source_stem}_golden.c"
    reference_name = f"forge_golden_{top_function.name}"
    function_names = _defined_function_names(source_text)
    defines = _extract_defines(source_text)
    typedefs = _extract_typedefs(source_text)

    lines: list[str] = [
        "/* Generated by FORGE. This testbench checks several input cases. */",
        "#include <stdint.h>",
        "#include <stdio.h>",
        "#include <string.h>",
    ]
    lines.extend(_extract_local_includes(source_text))
    lines.append("")
    lines.extend(defines)
    lines.extend(typedefs)
    if defines or typedefs:
        lines.append("")
    lines.extend(
        [
            f"#define FORGE_TB_DEFAULT_SIZE {DEFAULT_TEST_SIZE}",
            f"#define FORGE_TB_CASE_COUNT {len(scenarios)}",
            "",
        ]
    )
    # Rename every source function in the reference copy to avoid linker conflicts.
    for name in function_names:
        lines.append(f"#define {name} forge_golden_{name}")
    lines.append(f'#include "{golden_name}"')
    for name in reversed(function_names):
        lines.append(f"#undef {name}")
    lines.extend(["", *_prototype_lines(top_function), ""])
    lines.extend(_scenario_helpers(scenarios, seed))
    lines.append("")
    lines.extend(_storage_lines(specs))
    lines.append("")
    lines.extend(_comparison_helpers(specs, top_function))
    lines.append("")
    lines.append("static int forge_run_case(int case_id) {")
    lines.extend(_initialization_lines(specs))
    lines.extend(_scalar_lines(specs))
    lines.extend(_call_lines(top_function, specs, reference_name))
    lines.extend(_result_check_lines(top_function, specs))
    lines.append("    return 0;")
    lines.append("}")
    lines.extend(
        [
            "",
            "int main(void) {",
            "    int failures = 0;",
            "    for (int case_id = 0; case_id < FORGE_TB_CASE_COUNT; ++case_id) {",
            "        failures += forge_run_case(case_id);",
            "    }",
            "    if (failures != 0) {",
            '        printf("FORGE testbench failed: %d case(s)\\n", failures);',
            "        return 1;",
            "    }",
            '    printf("FORGE testbench passed: %d case(s)\\n", FORGE_TB_CASE_COUNT);',
            "    return 0;",
            "}",
        ]
    )

    manifest = {
        "version": 1,
        "profile": profile,
        "seed": seed,
        "oracle": "original_b0_source",
        "comparison": "return value and all array or pointer parameters",
        "case_count": len(scenarios),
        "cases": [scenario.name for scenario in scenarios],
        "parameters": [
            {
                "name": spec.name,
                "type": spec.storage_type,
                "dimensions": spec.dimensions,
                "pointer": spec.is_pointer,
                "direction": spec.direction,
            }
            for spec in specs
        ],
        "limitations": [
            "Input ranges are inferred from the C interface and may not include every legal value.",
            "External files, global side effects, pointer alias rules and protocol timing are not inferred.",
            "A user testbench is still required when the inferred interface contract is incomplete.",
        ],
    }
    return TestbenchSource(
        filename=f"{source_stem}_tb.c",
        source="\n".join(lines) + "\n",
        support_files={
            golden_name: _reference_source(
                source_text,
                defines,
                typedefs,
                keep_main=top_function.name == "main",
            )
        },
        manifest=manifest,
    )


def _scenarios_for_profile(profile: str) -> list[TestbenchScenario]:
    scenarios = [TestbenchScenario("random_nominal", "random", "full", 1)]
    if profile == "smoke":
        return scenarios
    scenarios = [
        TestbenchScenario("all_zero", "zero", "minimum"),
        TestbenchScenario("all_one", "one", "small"),
        TestbenchScenario("ascending", "ascending", "half"),
        TestbenchScenario("alternating_sign", "alternating", "full"),
        TestbenchScenario("first_impulse", "first_impulse", "full"),
        TestbenchScenario("random_nominal", "random", "full", 1),
    ]
    if profile == "standard":
        return scenarios
    return scenarios + [
        TestbenchScenario("all_negative_one", "negative_one", "small"),
        TestbenchScenario("descending", "descending", "near_full"),
        TestbenchScenario("last_impulse", "last_impulse", "full"),
        TestbenchScenario("sparse", "sparse", "full"),
        TestbenchScenario("low_values", "low", "half"),
        TestbenchScenario("high_values", "high", "full"),
        TestbenchScenario("random_second_seed", "random", "full", 97),
    ]


def _scenario_helpers(scenarios: list[TestbenchScenario], seed: int) -> list[str]:
    pattern_ids = {
        "zero": 0,
        "one": 1,
        "negative_one": 2,
        "ascending": 3,
        "descending": 4,
        "alternating": 5,
        "first_impulse": 6,
        "last_impulse": 7,
        "sparse": 8,
        "low": 9,
        "high": 10,
        "random": 11,
    }
    size_ids = {"minimum": 0, "small": 1, "half": 2, "near_full": 3, "full": 4}
    patterns = ", ".join(str(pattern_ids[item.pattern]) for item in scenarios)
    sizes = ", ".join(str(size_ids[item.size_mode]) for item in scenarios)
    offsets = ", ".join(str(item.seed_offset) for item in scenarios)
    return [
        f"static const int forge_patterns[FORGE_TB_CASE_COUNT] = {{{patterns}}};",
        f"static const int forge_sizes[FORGE_TB_CASE_COUNT] = {{{sizes}}};",
        f"static const unsigned int forge_seed_offsets[FORGE_TB_CASE_COUNT] = {{{offsets}}};",
        "",
        "static unsigned int forge_random_value(unsigned int value) {",
        "    return value * 1664525u + 1013904223u;",
        "}",
        "",
        "static long long forge_pattern_value(int case_id, int index, int count, int salt) {",
        "    int pattern = forge_patterns[case_id];",
        "    if (pattern == 0) return 0;",
        "    if (pattern == 1) return 1;",
        "    if (pattern == 2) return -1;",
        "    if (pattern == 3) return (index + salt) % 17;",
        "    if (pattern == 4) return 16 - ((index + salt) % 17);",
        "    if (pattern == 5) return ((index + salt) & 1) ? -7 : 7;",
        "    if (pattern == 6) return index == 0 ? 31 : 0;",
        "    if (pattern == 7) return index == count - 1 ? 31 : 0;",
        "    if (pattern == 8) return ((index + salt) % 7) == 0 ? 9 : 0;",
        "    if (pattern == 9) return ((index + salt) % 3) - 1;",
        "    if (pattern == 10) return 31 - ((index + salt) % 3);",
        f"    unsigned int state = {seed}u + forge_seed_offsets[case_id] +",
        "                         (unsigned int)(index * 131 + salt * 977);",
        "    return (long long)(forge_random_value(state) % 33u) - 16;",
        "}",
        "",
        "static int forge_active_size(int case_id, int capacity) {",
        "    int mode = forge_sizes[case_id];",
        "    if (capacity < 1) return 1;",
        "    if (mode == 0) return 1;",
        "    if (mode == 1) return capacity < 4 ? capacity : 4;",
        "    if (mode == 2) return capacity < 2 ? capacity : capacity / 2;",
        "    if (mode == 3) return capacity < 2 ? capacity : capacity - 1;",
        "    return capacity;",
        "}",
    ]


def _prototype_lines(function: FunctionAnalysis) -> list[str]:
    if not function.parameters:
        return [f"{function.return_type} {function.name}(void);"]
    lines = [f"{function.return_type} {function.name}("]
    for index, parameter in enumerate(function.parameters):
        suffix = "," if index < len(function.parameters) - 1 else ""
        lines.append(f"    {parameter}{suffix}")
    lines.append(");")
    return lines


def _storage_lines(specs: list[ParameterSpec]) -> list[str]:
    lines: list[str] = []
    for spec in specs:
        if not spec.has_storage:
            continue
        dimensions = _storage_dimensions(spec)
        lines.append(f"static {spec.storage_type} {spec.name}_ref{dimensions};")
        lines.append(f"static {spec.storage_type} {spec.name}_dut{dimensions};")
    return lines


def _initialization_lines(specs: list[ParameterSpec]) -> list[str]:
    lines: list[str] = []
    # Both functions must start with exactly the same data.
    for salt, spec in enumerate(specs, start=1):
        if not spec.has_storage:
            continue
        count = _element_count(spec.dimensions)
        lines.append(f"    for (int i = 0; i < {count}; ++i) {{")
        lines.append(
            f"        {spec.storage_type} value = ({spec.storage_type})"
            f"forge_pattern_value(case_id, i, {count}, {salt});"
        )
        lines.append(f"        (({spec.storage_type} *){spec.name}_ref)[i] = value;")
        lines.append(f"        (({spec.storage_type} *){spec.name}_dut)[i] = value;")
        lines.append("    }")
    return lines


def _scalar_lines(specs: list[ParameterSpec]) -> list[str]:
    capacity = _active_capacity(specs)
    lines: list[str] = []
    for salt, spec in enumerate(specs, start=1):
        if spec.has_storage:
            continue
        if _is_dimension_parameter(spec):
            value = "forge_active_size(case_id, 16)"
        elif _is_size_parameter(spec):
            value = f"forge_active_size(case_id, {capacity})"
        else:
            value = f"forge_nonzero_scalar(case_id, {salt})"
        lines.append(f"    {spec.storage_type} {spec.name} = ({spec.storage_type})({value});")
    return lines


def _comparison_helpers(
    specs: list[ParameterSpec],
    function: FunctionAnalysis,
) -> list[str]:
    lines = [
        "static int forge_nonzero_scalar(int case_id, int salt) {",
        "    int value = (int)forge_pattern_value(case_id, salt, 17, salt + 19);",
        "    return value == 0 ? 1 : value;",
        "}",
    ]
    types: list[tuple[str, str, bool]] = []
    for spec in specs:
        if spec.has_storage:
            types.append((f"param_{spec.name}", spec.storage_type, spec.is_floating_point))
    if function.return_type.strip() != "void":
        return_type = _strip_type_qualifiers(function.return_type)
        types.append(("return", return_type, _is_float_type(return_type)))
    for suffix, c_type, is_float in types:
        lines.extend(["", f"static int forge_same_{suffix}({c_type} left, {c_type} right) {{"])
        if is_float:
            # HLS floating-point results may differ by a small rounding error.
            lines.extend(
                [
                    "    long double difference = (long double)left - (long double)right;",
                    "    long double magnitude = (long double)left;",
                    "    if (difference < 0) difference = -difference;",
                    "    if (magnitude < 0) magnitude = -magnitude;",
                    "    return difference <= 0.00001L * (1.0L + magnitude);",
                ]
            )
        else:
            lines.append("    return memcmp(&left, &right, sizeof(left)) == 0;")
        lines.append("}")
    return lines


def _call_lines(
    function: FunctionAnalysis,
    specs: list[ParameterSpec],
    reference_name: str,
) -> list[str]:
    ref_args = ", ".join(
        f"{spec.name}_ref" if spec.has_storage else spec.name for spec in specs
    )
    dut_args = ", ".join(
        f"{spec.name}_dut" if spec.has_storage else spec.name for spec in specs
    )
    if function.return_type.strip() == "void":
        return [
            f"    {reference_name}({ref_args});" if ref_args else f"    {reference_name}();",
            f"    {function.name}({dut_args});" if dut_args else f"    {function.name}();",
        ]
    return [
        f"    {function.return_type} forge_reference_result = {reference_name}({ref_args});"
        if ref_args else f"    {function.return_type} forge_reference_result = {reference_name}();",
        f"    {function.return_type} forge_dut_result = {function.name}({dut_args});"
        if dut_args else f"    {function.return_type} forge_dut_result = {function.name}();",
    ]


def _result_check_lines(
    function: FunctionAnalysis,
    specs: list[ParameterSpec],
) -> list[str]:
    lines: list[str] = []
    if function.return_type.strip() != "void":
        lines.extend(
            [
                "    if (!forge_same_return(forge_reference_result, forge_dut_result)) {",
                '        printf("case %d: return value mismatch\\n", case_id);',
                "        return 1;",
                "    }",
            ]
        )
    for spec in specs:
        if not spec.has_storage:
            continue
        count = _element_count(spec.dimensions)
        lines.extend(
            [
                f"    for (int i = 0; i < {count}; ++i) {{",
                f"        {spec.storage_type} reference = (({spec.storage_type} *){spec.name}_ref)[i];",
                f"        {spec.storage_type} actual = (({spec.storage_type} *){spec.name}_dut)[i];",
                f"        if (!forge_same_param_{spec.name}(reference, actual)) {{",
                f'            printf("case %d: {spec.name}[%d] mismatch\\n", case_id, i);',
                "            return 1;",
                "        }",
                "    }",
            ]
        )
    return lines


def _parse_parameter(parameter: str) -> ParameterSpec:
    text = " ".join(parameter.strip().split())
    array_match = re.fullmatch(
        r"(?P<type>.+?)\s+(?P<name>[A-Za-z_]\w*)\s*(?P<dims>(?:\[[^\]]*\])+)",
        text,
    )
    if array_match:
        return ParameterSpec(
            raw=parameter,
            name=array_match.group("name"),
            c_type=array_match.group("type"),
            dimensions=re.findall(r"\[([^\]]*)\]", array_match.group("dims")),
        )
    pointer_match = re.fullmatch(r"(?P<type>.+?)\s*\*\s*(?P<name>[A-Za-z_]\w*)", text)
    if pointer_match:
        return ParameterSpec(
            raw=parameter,
            name=pointer_match.group("name"),
            c_type=pointer_match.group("type"),
            dimensions=[],
            is_pointer=True,
        )
    scalar_match = re.fullmatch(r"(?P<type>.+?)\s+(?P<name>[A-Za-z_]\w*)", text)
    if scalar_match:
        return ParameterSpec(
            raw=parameter,
            name=scalar_match.group("name"),
            c_type=scalar_match.group("type"),
            dimensions=[],
        )
    raise ValueError(f"Automatic testbench cannot parse parameter: {parameter}")


def _with_direction(spec: ParameterSpec, body: str) -> ParameterSpec:
    if not spec.has_storage:
        return spec
    if re.search(r"\bconst\b", spec.c_type):
        direction = "input"
    else:
        indexed = rf"\b{re.escape(spec.name)}\s*\[[^\]]+\]"
        pointer = rf"\*\s*{re.escape(spec.name)}\b"
        target = rf"(?:{indexed}|{pointer})"
        compound = bool(re.search(rf"{target}\s*(?:[+\-*/%&|^]=|\+\+|--)", body))
        write = bool(re.search(rf"{target}\s*(?:[+\-*/%&|^]?=|\+\+|--)", body))
        read = len(re.findall(indexed, body)) + len(re.findall(pointer, body)) > int(write)
        direction = "inout" if compound or (write and read) else "output" if write else "input"
    return ParameterSpec(
        raw=spec.raw,
        name=spec.name,
        c_type=spec.c_type,
        dimensions=spec.dimensions,
        is_pointer=spec.is_pointer,
        direction=direction,
    )


def _storage_dimensions(spec: ParameterSpec) -> str:
    if spec.is_pointer:
        return "[FORGE_TB_DEFAULT_SIZE]"
    return "".join(f"[{_dimension_or_default(dim)}]" for dim in spec.dimensions)


def _active_capacity(specs: list[ParameterSpec]) -> str:
    for spec in specs:
        if spec.is_array and spec.dimensions:
            return _dimension_or_default(spec.dimensions[0])
    return "FORGE_TB_DEFAULT_SIZE"


def _is_size_parameter(spec: ParameterSpec) -> bool:
    name = spec.name.lower()
    return any(word in name for word in ("size", "length", "count", "pixel")) or name == "n"


def _is_dimension_parameter(spec: ParameterSpec) -> bool:
    name = spec.name.lower()
    return name in {"width", "height", "rows", "columns", "row_count", "column_count"}


def _dimension_or_default(dimension: str) -> str:
    value = dimension.strip()
    return value if value else "FORGE_TB_DEFAULT_SIZE"


def _element_count(dimensions: list[str]) -> str:
    values = [_dimension_or_default(dimension) for dimension in dimensions]
    return " * ".join(values) if values else "FORGE_TB_DEFAULT_SIZE"


def _strip_type_qualifiers(c_type: str) -> str:
    words = [word for word in c_type.split() if word not in {"const", "volatile", "restrict"}]
    return " ".join(words) or "int"


def _is_float_type(c_type: str) -> bool:
    value = c_type.lower()
    return "float" in value or "double" in value


def _extract_function_body(source: str, function_name: str) -> str:
    match = re.search(rf"\b{re.escape(function_name)}\s*\([^;]*?\)\s*\{{", source, re.DOTALL)
    if not match:
        return ""
    start = source.find("{", match.start())
    end = _matching_brace(source, start)
    return source[start + 1:end] if end is not None else ""


def _defined_function_names(source: str) -> list[str]:
    pattern = re.compile(r"\b([A-Za-z_]\w*)\s*\([^;{}]*\)\s*\{", re.DOTALL)
    masked = _mask_comments_and_strings(source)
    masked = re.sub(
        r"(?m)^[ \t]*\#[^\n]*",
        lambda match: " " * len(match.group(0)),
        masked,
    )
    names = [match.group(1) for match in pattern.finditer(masked)]
    return list(dict.fromkeys(name for name in names if name not in {"if", "for", "while", "switch"}))


def _remove_main_function(source: str) -> str:
    masked = _mask_comments_and_strings(source)
    match = re.search(r"\bmain\s*\([^;{}]*\)\s*\{", masked, re.DOTALL)
    if not match:
        return source
    body_start = masked.find("{", match.start())
    body_end = _matching_brace(masked, body_start)
    if body_end is None:
        return source
    line_start = source.rfind("\n", 0, match.start()) + 1
    return source[:line_start] + source[body_end + 1:]


def _reference_source(
    source: str,
    defines: list[str],
    typedefs: list[str],
    keep_main: bool = False,
) -> str:
    reference = source if keep_main else _remove_main_function(source)
    # These declarations are already placed before the reference include.
    for declaration in [*defines, *typedefs]:
        reference = reference.replace(declaration, "", 1)
    return reference


def _extract_defines(source: str) -> list[str]:
    return re.findall(
        r"^\s*#define\s+[A-Za-z_]\w*(?:\([^\n)]*\))?[^\n]*",
        source,
        flags=re.MULTILINE,
    )


def _extract_typedefs(source: str) -> list[str]:
    return re.findall(r"^\s*typedef\b[^;]*;", source, flags=re.MULTILINE)


def _extract_local_includes(source: str) -> list[str]:
    return re.findall(r'^\s*(#include\s+"[^"]+")', source, flags=re.MULTILINE)


def _matching_brace(source: str, start: int) -> int | None:
    depth = 0
    for index in range(start, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return index
    return None


def _mask_comments_and_strings(source: str) -> str:
    pattern = re.compile(r'//[^\n]*|/\*.*?\*/|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'', re.DOTALL)
    return pattern.sub(lambda match: " " * len(match.group(0)), source)
